const pages = [
    { title: "He-Man and the Masters of the Universe", url: "PAGES/MOTU.html", keywords: "Heman motu masters eternia 1983 1984 1985 skeletor filmation marvel mattel"},
    { title: "G.I. Joe", url: "PAGES/GIJoe.html", keywords: "GIJoe yo joe duke scarlett snake cobra hasbro 1982 1983 1984 1985 1986 1987 1988 1989 Sunbow Marvel" },
    { title: "ThunderCats", url: "PAGES/ThunderCats.html", keywords: "thunder cats thundercats mumm-ra lion-o tigra cheetara thundera panthro 1985 1986 1987 1988 1989 rankin bass ljn star"},
    { title: "Beverly Hills Teens", url: "PAGES/Beverly Hills Teens.html", keywords: "beverly hills teens dic 1987 bianca wilshire larke chester pierce troy" },
    { title: "Bionic Six", url: "PAGES/Bionic6.html", keywords: "bionic six sport iq mother rock karate one scarab madame glove mechanic klunk tokyo movie shinsha ljn 1987" },
    { title: "Blackstar", url: "PAGES/Blackstar.html", keywords: "filmation black star trobbit overlord sagar 1981 john galoob" },
    { title: "BraveStarr", url: "PAGES/BraveStarr.html", keywords: "brave star bravestarr filmation marshall tex hex 3030 thirty thirtythirty mattel" },
    { title: "The Centurions", url: "PAGES/Centurions.html", keywords: "centurions kenner ruby spears ace mcleod max ray jake rockwell doc terror powerXtreme" },
    { title: "Defenders of the Earth", url: "PAGES/DefendersoftheEarth.html", keywords: "defender" },
    { title: "Denver the Last Dinosaur", url: "PAGES/Denver the Last Dinosaur.html", keywords: "denver"  },
    { title: "Dino-Riders", url: "PAGES/DinoRiders.html", keywords: "dino" },
    { title: "Dinosaucers", url: "PAGES/Dinosaucers.html", keywords: "dino" },
    { title: "Disney's DuckTales", url: "PAGES/DuckTales.html", keywords: "disney duck tales scrooge mcduck huey dewey louis webbigail flinthart glomgold gizmoduck 1987" },
    { title: "Dungeons & Dragons", url: "PAGES/Dungeons&Dragons.html", keywords: "dungeons dragons d&d TSR marvel sunbow sheila bobby eric master venger orc diana presto hank 1983" },
    { title: "Filmation's Ghostbusters", url: "PAGES/FilmationsGhostbusters.html", keywords: "filmation ghostbusters ghost gorilla jake eddie tracy 1986" },
    { title: "Heathcliff and the Catillac Cats", url: "PAGES/Heathcliff.html", keywords: "cat" },
    { title: "Hulk Hogan's Rock N' Wrestling", url: "PAGES/HulkHoganRNW.html", keywords: "hulk hogan wrestling rock albano rowdy roddy piper iron sheik wwf dic 1985" },
    { title: "Inspector Gadget", url: "PAGES/InspectorGadget.html", keywords: "inspector" },
    { title: "Jem and the Holograms", url: "PAGES/Jem.html", keywords: "jem" },
    { title: "My Little Pony N' Friends", url: "PAGES/My Little Pony N' Friends.html", keywords: "pony" },
    { title: "Pole Position", url: "PAGES/PolePosition.html", keywords: "pole" },
    { title: "Rainbow Brite", url: "PAGES/Rainbow Brite.html", keywords: "rainbow" },
    { title: "Sectaurs: Warriors of Symbion", url: "PAGES/Sectaurs.html", keywords: "sectaurs" },
    { title: "SilverHawks", url: "PAGES/SilverHawks.html", keywords: "silver" },
    { title: "M.A.S.K.", url: "PAGES/mask.html", keywords: "mask" },
  { title: "Voltron", url: "PAGES/voltron.html", keywords: "voltron" }
];

